language: go
go_import_path: github.com/alecrabbit/go-cli-spinner

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -cover ./...
  - $GOPATH/bin/goveralls -service=travis-ci

matrix:
  include:
    - go: 1.11.x
      env: GO111MODULE=on
    - go: 1.12.x
    - go: 1.13.x
    - go: master
  allow_failures:
    - go: master

cache:
  directories:
    - $GOPATH/pkg

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
