language: go
go_import_path: github.com/alecrabbit/go-cli-spinner

before_install:
  - go get github.com/mattn/goveralls

install:
  - echo 'idle'

script:
  - go test -v -cover ./...
  - $GOPATH/bin/goveralls -service=travis-ci
go:
  - 1.13.x
  - master

cache:
  directories:
    - $GOPATH/pkg

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
