language: go
go_import_path: github.com/alecrabbit/go-cli-spinner

install:
  - echo 'idle'

script:
  - go test -v -cover ./...

go:
  - 1.13.x
  - master

cache:
  directories:
    - $GOPATH/pkg

after_success:
  - bash <(curl -s https://codecov.io/bash)
